export const SET_CURRENT_CONTENT = 'SET_CURRENT_CONTENT';
export const SET_PREVIOUS_MENU_ID = 'SET_PREVIOUS_MENU_ID';
export const SET_PREVIOUS_MENU_ITEM_ID = 'SET_PREVIOUS_MENU_ITEM_ID';
export const SET_MAIN_MENU_ID = 'SET_MAIN_MENU_ID';
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
